name: yarndesktopclient
description: "A desktop client for yarn.social instances."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  http: ^1.2.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.0.9
  file_picker: ^8.0.0+1
  flutter_secure_storage: ^9.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
